<?xml version="1.0"?>
<robot name="robot_base" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="robot_width" value="0.57375" />
  <xacro:property name="robot_length" value="0.5032"/>
  <xacro:property name="robot_height" value="0.2238375"/>

  <xacro:property name="body_width" value="0.4016" />
  <xacro:property name="body_length" value="0.5032"/>
  <xacro:property name="body_height" value="0.08255"/>

  <xacro:property name="wheel_radius" value="0.066675"/>
  <xacro:property name="wheel_width" value="0.05715"/>
  <xacro:property name="wheelbase" value="0.4826"/>

  <xacro:macro name="robot_wheel" params="prefix number">
    <link name="${prefix}_wheel_${number}">
      <inertial>
        <origin rpy="0.0 ${pi/2} 0.0"/>
        <mass value="0.0"/>
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
      </inertial>
      <visual name="wheel">
        <origin rpy="0.0 ${pi/2} 0.0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="blue">
          <color rgba="0.0 0.0 1.0 1.0"/>
        </material>
      </visual>
    </link>
  </xacro:macro>

  <xacro:macro name="wheel_joint" params="prefix reflect number">
    <xacro:robot_wheel prefix="${prefix}" number="${number}"/>
    <joint name="${prefix}_wheel_${number}_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_${number}"/>
      <!--axis xyz="0.0 1.0 0.0"/-->
      <origin xyz="${((robot_width/2) - (wheel_width/2))*reflect} ${(wheelbase/2 - wheel_radius)*(number-2)*-1} ${wheel_radius}"/>
    </joint>
  </xacro:macro>

  <link name="base_link">
    <collision>
      <geometry>
        <box size="${robot_width} ${robot_length} ${robot_height}"/>
      </geometry>
    </collision>
  </link>

  <link name="body">
    <visual>
      <geometry>  
        <box size="${body_width} ${body_length} ${body_height}"/>
      </geometry>
    </visual>
  </link>

  <joint name="body_link" type="fixed">
    <parent link="base_link"/>
    <child link="body"/>
    <origin xyz="0 0 ${robot_height - body_height/2}"/>
  </joint>

  <!--Create all the wheels and define all the wheel joints-->
  <xacro:wheel_joint prefix="left" reflect="-1" number="1"/>
  <xacro:wheel_joint prefix="left" reflect="-1" number="2"/>
  <xacro:wheel_joint prefix="left" reflect="-1" number="3"/>
  <xacro:wheel_joint prefix="right" reflect="1" number="1"/>
  <xacro:wheel_joint prefix="right" reflect="1" number="2"/>
  <xacro:wheel_joint prefix="right" reflect="1" number="3"/>

  <!--Import the 435 model-->
  <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro"/>
  <xacro:arg name="use_nominal_extrinsics" default="True" />

  <!--Define offsets relative to the robot frame-->
  <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149"/>
  <!-- glass cover is 0.1 mm inwards from front aluminium plate -->
  <xacro:property name="glass_to_front" value="0.1e-3"/>
  <!-- see datasheet Revision 007, Fig. 4-4 page 65 -->
  <xacro:property name="zero_depth_to_glass" value="4.2e-3"/>
  <!-- convenience precomputation to avoid clutter-->
  <xacro:property name="d435_offset_y" value="${d435_cam_mount_from_center_offset-glass_to_front-zero_depth_to_glass}"/>
  <xacro:property name="offset_435_x" value="${body_width/2 - 0.2032}"/>
  <xacro:property name="mount_offset_435" value="0.0111125"/>

  <xacro:sensor_d435 parent="body">
    <origin xyz="${offset_435_x} ${body_length/2 + d435_offset_y + mount_offset_435} ${body_height/2 - 0.0254}" rpy="0 0 ${pi/2}"/>
  </xacro:sensor_d435>

  <xacro:include filename="$(find realsense2_description)/urdf/_t265.urdf.xacro"/>

  <xacro:sensor_t265 parent="body">
    <origin xyz="0.0 ${body_length/2 + 0.0508} 0.0" rpy="0.0 0.0 0.0"/>
  </xacro:sensor_t265>

</robot>
